name: "Build and Push"
on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  build:
    name: build
    runs-on: self-hosted
    steps:
      - name: Checkout Local Source Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GHE_TOKEN }}
          
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.aws_region }}

      - name: Deploy code to s3 bucket
        run: |
          zip -r ${{ github.event.repository.name }}.zip *
          aws s3 cp ${{ github.event.repository.name }}.zip s3://${{ vars.s3_bucket }}/${{ vars.s3_key }}